# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2022-04-26 20:55+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 3.0.1\n"
"X-Poedit-Basepath: ..\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPathExcluded-0: tests\n"

#: _error.py:13
msgid "The file lock '{}' could not be acquired. Is another instance of pleroma-bot running?"
msgstr ""

#: _misskey.py:80
msgid "Post in Misskey:\t{}"
msgstr ""

#: _misskey.py:116 _pleroma.py:43
msgid "No posts were found in the target Fediverse account"
msgstr ""

#: _misskey.py:178 _pleroma.py:107
#, python-brace-format
msgid ""
"Exception occurred\n"
"Media size too large:\n"
"Filename: {file}\n"
"Size: {size}MB\n"
"Consider increasing the attachment\n"
" size limit of your instance"
msgstr ""

#: _misskey.py:193 _pleroma.py:122
#, python-brace-format
msgid ""
"Exception occurred\n"
"Unprocessable Entity\n"
"{error}\n"
"File: {file}"
msgstr ""

#: _misskey.py:261 _pleroma.py:235
msgid ""
"Total number of metadata fields cannot exceed 4.\n"
"Provided: {}. Exiting..."
msgstr ""

#: _misskey.py:288 _pleroma.py:273
msgid ""
"Exception occurred\n"
"Error code 422\n"
"(Unprocessable Entity)\n"
"Please check that the bio text or the metadata fields text\n"
"aren't too long."
msgstr ""

#: _misskey.py:298 _pleroma.py:283
msgid "Updating profile:\t {}"
msgstr ""

#: _pin.py:35 _pin.py:137
msgid "Pinning post:\t{}"
msgstr ""

#: _pin.py:73 _pin.py:171
msgid "Unpinning previous:\t{}"
msgstr ""

#: _pin.py:77 _pin.py:175
msgid "File with previous pinned post ID not found or empty. Checking last posts for pinned post..."
msgstr ""

#: _pin.py:84 _pin.py:182
msgid "Unpinned: {}"
msgstr ""

#: _pin.py:86 _pin.py:184
msgid "Pinned post not found. Giving up unpinning..."
msgstr ""

#: _pleroma.py:135
msgid "Error uploading media:\t{}"
msgstr ""

#: _pleroma.py:171
msgid "Post in Pleroma:\t{}"
msgstr ""

#: _processing.py:184
msgid "Post text longer than allowed ({}), truncating..."
msgstr ""

#: _processing.py:255
msgid "Giving up, reference is too deep"
msgstr ""

#: _processing.py:319
#, python-brace-format
msgid ""
"Exception occurred\n"
"Media not found (404)\n"
"{tweet} - {media_url}\n"
"Ignoring attachment and continuing..."
msgstr ""

#: _processing.py:344
msgid "Attachment exceeded config file size limit ({})"
msgstr ""

#: _processing.py:348
msgid "File size: {}MB"
msgstr ""

#: _processing.py:352
msgid "Ignoring attachment and continuing..."
msgstr ""

#: _processing.py:444
msgid "Couldn't expand the url {}: {}"
msgstr ""

#: _processing.py:455
msgid "Couldn't expand the url: {}"
msgstr ""

#: _twitter.py:35
msgid "Rate limit exceeded. 0 out of {} requests remaining until {} UTC"
msgstr ""

#: _twitter.py:40
msgid "Sleeping for {}s..."
msgstr ""

#: _twitter.py:201
msgid "API version not supported: {}"
msgstr ""

#: _twitter.py:217
msgid "max_tweets must be between 10 and 3200. max_tweets: {}"
msgstr ""

#: _twitter.py:371
msgid "Gathering tweets... "
msgstr ""

#: _utils.py:142
msgid "Processing tweets... "
msgstr ""

#: _utils.py:205
msgid "Attempting to acquire lock {} on {}"
msgstr ""

#: _utils.py:212
msgid "Lock {} acquired on {}"
msgstr ""

#: _utils.py:218
msgid "Timeout on acquiring lock {} on {}"
msgstr ""

#: _utils.py:224
msgid "Lock {} not acquired on {}, waiting {} seconds ..."
msgstr ""

#: _utils.py:259
msgid "Attempting to release lock {} on {}"
msgstr ""

#: _utils.py:264
msgid "Lock {} released on {}"
msgstr ""

#: _utils.py:318
msgid "Current pinned:\t{}"
msgstr ""

#: _utils.py:329
msgid "Previous pinned:\t{}"
msgstr ""

#: _utils.py:468
msgid "Instance appears to be Misskey ฅ^•ﻌ•^ฅ"
msgstr ""

#: _utils.py:474
msgid "Instance response was not understood {}"
msgstr ""

#: _utils.py:479
msgid "Target instance is Mastodon..."
msgstr ""

#: _utils.py:489
msgid "Mastodon doesn't support display names longer than 30 characters, truncating it and trying again..."
msgstr ""

#: _utils.py:497
msgid "Mastodon doesn't support rich text. Disabling it..."
msgstr ""

#: _utils.py:503
msgid "How far back should we retrieve tweets from the Twitter account?"
msgstr ""

#: _utils.py:506
msgid ""
"\n"
"Enter a date (YYYY-MM-DD):\n"
"[Leave it empty to retrieve *ALL* tweets or enter 'continue'\n"
"if you want the bot to execute as normal (checking date of \n"
"last post in the Fediverse account)] "
msgstr ""

#: _utils.py:522 _utils.py:529
msgid "Raising max_tweets to the maximum allowed value"
msgstr ""

#: cli.py:167
msgid "No Pleroma URL defined in config! [pleroma_base_url]"
msgstr ""

#: cli.py:195
msgid "Some or all OAuth 1.0a tokens missing, falling back to application-only authentication"
msgstr ""

#: cli.py:236 cli.py:245
msgid "Visibility not supported! Values allowed are: {}"
msgstr ""

#: cli.py:260
msgid "Bot for mirroring one or multiple Twitter accounts in Pleroma/Mastodon."
msgstr ""

#: cli.py:273
msgid "path of config file (config.yml) to use and parse. If not specified, it will try to find it in the current working directory."
msgstr ""

#: cli.py:287
msgid "run in daemon mode. By default it will re-run every 60min. You can control this with --pollrate"
msgstr ""

#: cli.py:300
msgid "only applies to daemon mode. How often to run the program in the background (in minutes). By default is 60min."
msgstr ""

#: cli.py:312
msgid "path of log file (error.log) to create. If not specified, it will try to store it at your config file path"
msgstr ""

#: cli.py:325
msgid "skips Fediverse profile update (no background image, profile image, bio text, etc.)"
msgstr ""

#: cli.py:339
msgid "forces the tweet retrieval to start from a specific date. The twitter_username value (FORCEDATE) can be supplied to only force it for that particular user in the config. Instead of the twitter_username a date (YYYY-MM-DD) can also be supplied to force that date for *all* users"
msgstr ""

#: cli.py:354
msgid "skips first run checks"
msgstr ""

#: cli.py:364
msgid "path of the Twitter archive file (zip) to use for posting tweets."
msgstr ""

#: cli.py:391
msgid "Debug logging enabled"
msgstr ""

#: cli.py:401
msgid "config path: {}"
msgstr ""

#: cli.py:402
msgid "tweets temp folder: {}"
msgstr ""

#: cli.py:425
msgid "Multiple twitter users for one Fediverse account, skipping profile and pinned tweet."
msgstr ""

#: cli.py:437
msgid "Processing user:\t{}"
msgstr ""

#: cli.py:448
msgid "It seems like pleroma-bot is running for the first time for this Twitter user: {}"
msgstr ""

#: cli.py:471
msgid "Invalid forceDate format, use \"YYYY-mm-dd\""
msgstr ""

#: cli.py:517
msgid ""
"Unable to retrieve tweets. Is the account protected? If so, you need to provide the following OAuth 1.0a fields in the user config:\n"
" - consumer_key \n"
" - consumer_secret \n"
" - access_token_key \n"
" - access_token_secret"
msgstr ""

#: cli.py:527
msgid "tweets gathered: \t {}"
msgstr ""

#: cli.py:535
msgid "tweets to post: \t {}"
msgstr ""

#: cli.py:562
msgid "Multiple twitter users, not updating profile"
msgstr ""

#: cli.py:571
msgid "Exception occurred for user, skipping..."
msgstr ""

#: cli.py:577
msgid "Exception occurred"
msgstr ""
