# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: pleroma-bot\n"
"POT-Creation-Date: 2022-04-26 21:02+0200\n"
"PO-Revision-Date: 2022-04-26 21:02+0200\n"
"Last-Translator: robertoszek <robertoszek@robertoszek.xyz>\n"
"Language-Team: \n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 3.0.1\n"
"X-Poedit-Basepath: ../../..\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPathExcluded-0: tests\n"

#: _error.py:13
msgid ""
"The file lock '{}' could not be acquired. Is another instance of pleroma-bot "
"running?"
msgstr ""
"El bloqueo del fichero '{}' no pudo ser adquirido. ¿Hay otra instancia de "
"pleroma-bot en ejecución?"

#: _misskey.py:80
msgid "Post in Misskey:\t{}"
msgstr "Publicando en Misskey\t{}"

#: _misskey.py:116 _pleroma.py:43
msgid "No posts were found in the target Fediverse account"
msgstr "No se han encontrado posts en la cuenta de Fediverso objectivo"

#: _misskey.py:178 _pleroma.py:107
#, python-brace-format
msgid ""
"Exception occurred\n"
"Media size too large:\n"
"Filename: {file}\n"
"Size: {size}MB\n"
"Consider increasing the attachment\n"
" size limit of your instance"
msgstr ""
"Se ha producido una excepción\n"
"Tamaño demasiado grande:\n"
"Nombre de fichero: {file}\n"
"Tamaño: {size}MB\n"
"Considere aumentar el límite de\n"
" tamaño de adjuntos para su instancia"

#: _misskey.py:193 _pleroma.py:122
#, python-brace-format
msgid ""
"Exception occurred\n"
"Unprocessable Entity\n"
"{error}\n"
"File: {file}"
msgstr ""
"Se produjo una excepción\n"
"Entidad no procesable\n"
"{error}\n"
"Archivo: {file}"

#: _misskey.py:261 _pleroma.py:235
msgid ""
"Total number of metadata fields cannot exceed 4.\n"
"Provided: {}. Exiting..."
msgstr ""
"El número de campos de metadatos no puede ser superior a 4.\n"
"Se han introducido {}. Saliendo..."

#: _misskey.py:288 _pleroma.py:273
msgid ""
"Exception occurred\n"
"Error code 422\n"
"(Unprocessable Entity)\n"
"Please check that the bio text or the metadata fields text\n"
"aren't too long."
msgstr ""
"Se produjo una excepción\n"
"Código de error 422\n"
"(Entidad no procesable)\n"
"Por favor compruebe que el texto de biografía o el texto de los campos de "
"metadatos\n"
"no se muy largo."

#: _misskey.py:298 _pleroma.py:283
msgid "Updating profile:\t {}"
msgstr "Actualizando perfil:\t{}"

#: _pin.py:35 _pin.py:137
msgid "Pinning post:\t{}"
msgstr "Fijando post:\t{}"

#: _pin.py:73 _pin.py:171
msgid "Unpinning previous:\t{}"
msgstr "Desfijando anterior:\t{}"

#: _pin.py:77 _pin.py:175
msgid ""
"File with previous pinned post ID not found or empty. Checking last posts "
"for pinned post..."
msgstr ""
"No se ha encontrado el archivo con el ID del anterior post fijado. Revisando "
"últimos posts..."

#: _pin.py:84 _pin.py:182
msgid "Unpinned: {}"
msgstr "Desfijado:\t{}"

#: _pin.py:86 _pin.py:184
msgid "Pinned post not found. Giving up unpinning..."
msgstr "Post fijado no encontrado. Dejamos de intentar el desfijado..."

#: _pleroma.py:135
msgid "Error uploading media:\t{}"
msgstr "Error mientras subiendo contenido:\t{}"

#: _pleroma.py:171
msgid "Post in Pleroma:\t{}"
msgstr "Publicando en Pleroma\t{}"

#: _processing.py:184
msgid "Post text longer than allowed ({}), truncating..."
msgstr "El texto del post es más largo que el permitido ({}), truncando..."

#: _processing.py:255
msgid "Giving up, reference is too deep"
msgstr "Dándose por vencido, la referencia está demasiado anidada"

#: _processing.py:319
#, python-brace-format
msgid ""
"Exception occurred\n"
"Media not found (404)\n"
"{tweet} - {media_url}\n"
"Ignoring attachment and continuing..."
msgstr ""
"Se ha producido una excepción\n"
"Contenido no encontrado (404)\n"
"{tweet} - {media_url}\n"
"Ignorando el adjunto y continuando..."

#: _processing.py:344
msgid "Attachment exceeded config file size limit ({})"
msgstr "Contenido adjunto ha excedido el límite configurado ({})"

#: _processing.py:348
msgid "File size: {}MB"
msgstr "Tamaño de fichero: {}MB"

#: _processing.py:352
msgid "Ignoring attachment and continuing..."
msgstr "Ignorando adjunto y continuando..."

#: _processing.py:444
msgid "Couldn't expand the url {}: {}"
msgstr "No se pudo expandir la URL {}: {}"

#: _processing.py:455
msgid "Couldn't expand the url: {}"
msgstr "No se pudo expandir la URL: {}"

#: _twitter.py:35
msgid "Rate limit exceeded. 0 out of {} requests remaining until {} UTC"
msgstr "Límite excedido. 0 de {} peticiones restantes hasta {} UTC"

#: _twitter.py:40
msgid "Sleeping for {}s..."
msgstr "Esperando {} segundos..."

#: _twitter.py:201
msgid "API version not supported: {}"
msgstr "Versión de API no soportada: {}"

#: _twitter.py:217
msgid "max_tweets must be between 10 and 3200. max_tweets: {}"
msgstr "El valor de max_tweets debe estar entre 10 y 3200. max_tweets: {}"

#: _twitter.py:371
msgid "Gathering tweets... "
msgstr "Recopilando tweets... "

#: _utils.py:142
msgid "Processing tweets... "
msgstr "Procesando tweets... "

#: _utils.py:205
msgid "Attempting to acquire lock {} on {}"
msgstr "Intentando adquirir el bloqueo {} en {}"

#: _utils.py:212
msgid "Lock {} acquired on {}"
msgstr "Bloqueo {} adquirido en {}"

#: _utils.py:218
msgid "Timeout on acquiring lock {} on {}"
msgstr "Tiempo de espera excedido al intentar adquirir el bloqueo {} en {}"

#: _utils.py:224
msgid "Lock {} not acquired on {}, waiting {} seconds ..."
msgstr "Bloqueo {} no adquirido en {}, esperando {} segundos ..."

#: _utils.py:259
msgid "Attempting to release lock {} on {}"
msgstr "Intentando liberar el bloqueo {} en {}"

#: _utils.py:264
msgid "Lock {} released on {}"
msgstr "Bloqueo {} liberado en {}"

#: _utils.py:318
msgid "Current pinned:\t{}"
msgstr "Fijado actualmente:\t{}"

#: _utils.py:329
msgid "Previous pinned:\t{}"
msgstr "Fijado anteriormente:\t{}"

#: _utils.py:468
msgid "Instance appears to be Misskey ฅ^•ﻌ•^ฅ"
msgstr "La instancia parecer tipo Misskey ฅ^•ﻌ•^ฅ"

#: _utils.py:474
msgid "Instance response was not understood {}"
msgstr "La respuesta de la instancia no ha podido ser interpretada {}"

#: _utils.py:479
msgid "Target instance is Mastodon..."
msgstr "La instancia objetivo es Mastodon..."

#: _utils.py:489
msgid ""
"Mastodon doesn't support display names longer than 30 characters, truncating "
"it and trying again..."
msgstr ""
"Mastodon no soporta nombres para mostrar de más de 30 caracteres, "
"truncándolo e intentándolo de nuevo..."

#: _utils.py:497
msgid "Mastodon doesn't support rich text. Disabling it..."
msgstr "Mastodon no soporta texto enriquecido. Desactivándolo..."

#: _utils.py:503
msgid "How far back should we retrieve tweets from the Twitter account?"
msgstr "¿Desde cuándo deberíamos recopilar los tweets de la cuenta de Twitter?"

#: _utils.py:506
msgid ""
"\n"
"Enter a date (YYYY-MM-DD):\n"
"[Leave it empty to retrieve *ALL* tweets or enter 'continue'\n"
"if you want the bot to execute as normal (checking date of \n"
"last post in the Fediverse account)] "
msgstr ""
"\n"
"Introduce una fecha (AAAA-MM-DD):\n"
"[Déjalo en blanco si quieres que se recopilen *TODOS*\n"
"los tweets ó introduce 'continue' si quieres que el bot se\n"
"comporte como de costumbre (comprobando la fecha del\n"
"último post de la cuenta del Fediverso)] "

#: _utils.py:522 _utils.py:529
msgid "Raising max_tweets to the maximum allowed value"
msgstr "Aumentando max_tweets al valor máximo admitido"

#: cli.py:167
msgid "No Pleroma URL defined in config! [pleroma_base_url]"
msgstr ""
"¡No se ha definido la URL de Pleroma en la configuración! [pleroma_base_url]"

#: cli.py:195
msgid ""
"Some or all OAuth 1.0a tokens missing, falling back to application-only "
"authentication"
msgstr ""
"No todos los tokens OAuth 1.0a han sido encontrados. Usando autenticación de "
"aplicación en su lugar"

#: cli.py:236 cli.py:245
msgid "Visibility not supported! Values allowed are: {}"
msgstr "Visibilidad introducida no soportada. Valores válidos: {}"

#: cli.py:260
msgid "Bot for mirroring one or multiple Twitter accounts in Pleroma/Mastodon."
msgstr "Bot para replicar una o varias cuentas de Twitter en Pleroma/Mastodon."

#: cli.py:273
msgid ""
"path of config file (config.yml) to use and parse. If not specified, it will "
"try to find it in the current working directory."
msgstr ""
"ruta del fichero de configuración (config.yml) a usar e interpretar. Si no "
"se especifica, se intentará usar el del directorio de trabajo actual."

#: cli.py:287
msgid ""
"run in daemon mode. By default it will re-run every 60min. You can control "
"this with --pollrate"
msgstr ""
"correr en modo daemon. Por defecto será relanzado cada 60 minutos. Puede "
"controlar la frecuencia con --pollrate"

#: cli.py:300
msgid ""
"only applies to daemon mode. How often to run the program in the background "
"(in minutes). By default is 60min."
msgstr ""
"sólo aplica a modo daemon. Frecuencia con la que correr el programa de fondo "
"(en minutos). Por defecto es 60 minutos."

#: cli.py:312
msgid ""
"path of log file (error.log) to create. If not specified, it will try to "
"store it at your config file path"
msgstr ""
"ruta del fichero de log (error.log) a escribir. Si no se especifica, se "
"intentará usar la ruta en la que se encuentra el fichero de configuración"

#: cli.py:325
msgid ""
"skips Fediverse profile update (no background image, profile image, bio "
"text, etc.)"
msgstr ""
"omite la actualización de perfil en la cuenta del Fediverso (imagen de "
"fondo, imagen de perfil, biografía, etc.)"

#: cli.py:339
msgid ""
"forces the tweet retrieval to start from a specific date. The "
"twitter_username value (FORCEDATE) can be supplied to only force it for that "
"particular user in the config. Instead of the twitter_username a date (YYYY-"
"MM-DD) can also be supplied to force that date for *all* users"
msgstr ""
"fuerza una fecha específica de comienzo para la recopilación de tweets. El "
"valor de twitter_username (FORCEDATE) puede ser introducido para forzar la "
"fecha de inicio de recopilación sólo para ese usuario específico del archivo "
"de configuración. En lugar de twitter_username se puede proporcionar una "
"fecha (AAAA-MM-DD) para forzar esa fecha en *todos* los usuarios"

#: cli.py:354
msgid "skips first run checks"
msgstr "omite las validaciones de la primera ejecución"

#: cli.py:364
msgid "path of the Twitter archive file (zip) to use for posting tweets."
msgstr ""
"ruta del fichero de archivo de Twitter (zip) a usar para publicar tweets."

#: cli.py:391
msgid "Debug logging enabled"
msgstr "Modo de depuración activado"

#: cli.py:401
msgid "config path: {}"
msgstr "ruta de configuración: {}"

#: cli.py:402
msgid "tweets temp folder: {}"
msgstr "carpeta temporal de tweets: {}"

#: cli.py:425
msgid ""
"Multiple twitter users for one Fediverse account, skipping profile and "
"pinned tweet."
msgstr ""
"Varios usuarios de Twitter definidos para una cuenta de Fediverso, omitiendo "
"la actualización de perfil y tweet fijado."

#: cli.py:437
msgid "Processing user:\t{}"
msgstr "Procesando usuario:\t{}"

#: cli.py:448
msgid ""
"It seems like pleroma-bot is running for the first time for this Twitter "
"user: {}"
msgstr ""
"Parece que pleroma-bot está ejecutándose por primera vez para este usuario: "
"{}"

#: cli.py:471
msgid "Invalid forceDate format, use \"YYYY-mm-dd\""
msgstr "Formato inválido en forceDate, use \"AAAA-MM-DD\" "

#: cli.py:517
msgid ""
"Unable to retrieve tweets. Is the account protected? If so, you need to "
"provide the following OAuth 1.0a fields in the user config:\n"
" - consumer_key \n"
" - consumer_secret \n"
" - access_token_key \n"
" - access_token_secret"
msgstr ""
"No se han podido recopilar los tweets. ¿Está la cuenta protegida? Si lo "
"está, necesita proporcionar los siguientes valores de OAuth 1.0a en la "
"configuración:\n"
" - consumer_key \n"
" - consumer_secret \n"
" - access_token_key \n"
" - access_token_secret"

#: cli.py:527
msgid "tweets gathered: \t {}"
msgstr "tweets recopilados: \t {}"

#: cli.py:535
msgid "tweets to post: \t {}"
msgstr "tweets a publicar: \t {}"

#: cli.py:562
msgid "Multiple twitter users, not updating profile"
msgstr "Varios usuarios de Twitter, omitiendo actualizado de perfil"

#: cli.py:571
msgid "Exception occurred for user, skipping..."
msgstr "Se produjo una excepción para este usuario, omitiendo..."

#: cli.py:577
msgid "Exception occurred"
msgstr "Se produjo una excepción"
